### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sampart** [whiteoctober/BreadcrumbsBundle#106]
Hi,

Sam here, one of the current maintainers of this project.

Given that we no longer use Symfony in any of our active projects, it's becoming harder to give this plugin the time it needs.

Therefore, we're looking for new maintainer(s) for this project.

We'd like any new prospective maintainer to fork this project, and then once that fork has moved forward enough to give us confidence in your ownership, we would link to your fork prominently from the top of the README here, encouraging others to use it instead.

If you're interested, please go ahead and fork (if you haven't already) and start work!  If you've forked and would like others to help you, feel free to reply in this issue with details of your fork.

Please do reply here if you have questions.  Thanks in anticipation.

**Comment by mhujer** [comment]
Hello @sampart,

I finally managed to create a proper fork compatible with Symfony 4.3 and make a release: https://github.com/mhujer/BreadcrumbsBundle/releases/tag/1.5.0

#### Notes:
It is compatible only with Symfony 4.3+, as maintaining the compatibility with older Symfony versions is tricky. The old versions of the bundle are perfectly usable with Symfony versions up to 4.2.

**Comment by sampart** [comment]
Thanks @mhujer! I've added a link to your fork to the README.

**Comment by sampart** [comment]
@mhujer At some point, the `whiteoctober` organisation will be deleted, along with this repo. Before that point, your repo - which is currently a fork of this one - will be updated to become the "root" (parent) repository. There's nothing you need to do - this is just FYI - but do let me know if you have any questions. Thanks again for your maintainership.

**Comment by sampart** [comment]
On reflection, I'll actually move this repo somewhere else (and archive it) and update Packagist to point there, since this project in Packagist is still getting a lot of installs.

**Comment by mhujer** [comment]
@sampart Thanks for letting me know. Moving and archiving is definitely much better option than deleting.

**Comment by sampart** [comment]
Yeah, I was a bit naive about how far users had got in migrating! I've transferred this now. Thanks again
