### ISSUE TITLE
Add ability to pass route name instead of URL

### ISSUE THREAD

**Issue by tomhv** [whiteoctober/BreadcrumbsBundle#38]
Hey Rich,

Thanks for accepting PR #37.

Because I'm lazy sometimes, I'd love to be able to use the following format

    $this->get('white_october_breadcrumbs')
        ->addItem('Home', '_homepage')
        ->addItem('Customers', 'acme_customer')
        ->addItem($customer->getName(), $this->get('router')->generate(
            'acme_customer_show', array(
                'slug' => $customer->getSlug(),
        )))
    ;

instead of

    $this->get('white_october_breadcrumbs')
        ->addItem('Home', $this->get('router')->generate('_homepage'))
        ->addItem('Customers', $this->get('router')->generate('acme_customer'))
        ->addItem($customer->getName(), $this->get('router')->generate(
            'acme_customer_show', array(
                'slug' => $customer->getSlug(),
        )))
    ;

The third item is the same in both examples, by the way.

I'm pretty sure we can make this work with out breaking BC.  Let me know if you're interested in a PR.

Cheers,

Tom

**Comment by bocharsky-bw** [comment]
It will be a bit confusing and will require new dependency injection of `router`, so it will broke BC.

**Comment by tomhv** [comment]
Hi @bocharsky-bw,

I had thought of catching the exception if the router could not find the given route.  In that case, the assumption is that a URL was given.

If you make the router an optional argument, surely it will not break BC.

Tom

**Comment by bocharsky-bw** [comment]
I think idea is good. But what about if we add new method for it?
``` php
$this->get('white_october_breadcrumbs')
    ->addRouteItem('Home', 'homepage')
    ->addRouteItem('Customers', 'acme_customer')
    ->addRouteItem($customer->getName(), 'acme_customer_show', [
            'slug' => $customer->getSlug(),
    ])
;
```
We could generate route with parameters and it will be more clarify and improve performance as for me.

**Comment by tomhv** [comment]
That's a great compromise! +1

**Comment by bocharsky-bw** [comment]
Ok, I think we need to wait for approval by @richsage

**Comment by richsage** [comment]
Thanks all :-) I'm happy with the suggested compromise - @tomhv did you want to submit a PR for it?

**Comment by bocharsky-bw** [comment]
I can do it with PR

**Comment by tomhv** [comment]
Thanks, @bocharsky-bw and @richsage
