### ISSUE TITLE
Do we need an active maintainer?

### ISSUE THREAD

**Issue by bocharsky-bw** [whiteoctober/BreadcrumbsBundle#43]
Hi there!

@richsage Do we need an active maintainer here maybe?

**Comment by dbu** [comment]
@richsage this looks like kind of an implicit answer ;-)

considering to use this bundle in a project and looking over open issues, it seems an additional maintainer would do some good. @bocharsky-bw are you proposing yourself?

**Comment by bocharsky-bw** [comment]
@dbu I frequently used this bundle in my projects and I could help a bit with open issues and PRs.

**Comment by dbu** [comment]
sounds great. lets hope you can get the attention of @richsage or some other whiteoctober guy

**Comment by richsage** [comment]
@bocharsky-bw @dbu sounds good, given my current workload it's not always easy to find time to look at this :-) Will check and see if this is permitted but I don't see an issue. I'm away on annual leave until June 1st but will hopefully have an answer by then :)

**Comment by bocharsky-bw** [comment]
@richsage OK, I'll be in touch and open for discussions! :)

**Comment by helios-ag** [comment]
I was always wandered, why breadcrumbs bundle and pagerfanta have different packagist namespaces (white-october/whiteoctober)?

**Comment by sampart** [comment]
The short answer is that it's a mistake by the original creator - they should both have the same namespace, really!

**Comment by bocharsky-bw** [comment]
Hey @sampart I appreciate your reply but really have less time now, sorry!

**Comment by sampart** [comment]
No problem; thanks for getting back to me!
