### ISSUE TITLE
Quelle classe utiliser pour réduire les marges hautes ou basse?

### ISSUE THREAD

**Issue by mathias1981** [whiteoctober/BreadcrumbsBundle#44]
http://www.preprod.sphere-sante.com/incontinence/tena-lady.html
Est ce que j'ai une classe à dispo pour réduire les marges en dessous de 
8
produits trouvés pour :
Tena Lady

et en dessous des avis clients? 

Ca m'arrive de temps en temps, est ce qu'il y a une classe qui fonctionne partout?

**Comment by bocharsky-bw** [comment]
@mathias1981, your link required authorization by username and password.
And can you translate your issue to English, please?

**Comment by bocharsky-bw** [comment]
@richsage I think this issue may be closed because @mathias1981 don't reply

**Comment by richsage** [comment]
@mathias1981 Closing this as per @bocharsky-bw's comment - if your issue is still present, please reopen and submit in English if possible? Thanks :-)
