### ISSUE TITLE
Rewrite installation chapter of docs

### ISSUE THREAD

**Issue by bocharsky-bw** [whiteoctober/BreadcrumbsBundle#50]
What about to rewrite `Installation` chapter of the docs a bit? 
I think we must to notice that installation via Composer is preferred choice and move it upper.

**Comment by richsage** [comment]
Yeah, I don't think it's worth having the deps installation section anymore. If people are still using Symfony 2.0, they perhaps have bigger problems to address :-) Plus they'll be familiar with how to install it in that case.

**Comment by bocharsky-bw** [comment]
Ok, I'll try to rewrite it a bit with PR

**Comment by bocharsky-bw** [comment]
ping @richsage
