### ISSUE TITLE
Replace old array syntax with new one in docs

### ISSUE THREAD

**Issue by bocharsky-bw** [whiteoctober/BreadcrumbsBundle#55]
I believe better to use new array syntax `[]` in the docs. In other code we'll left old one `array()` for `BC`.
What do you think?

**Comment by richsage** [comment]
Yep - I don't have a preference either way. Those people using earlier versions will (hopefully) recognise the newer syntax!

**Comment by bocharsky-bw** [comment]
OK, after the all my docs PRs are merged I could create a new one for it.

**Comment by richsage** [comment]
Looks good! :-)
