### ISSUE TITLE
Close hanged PRs

### ISSUE THREAD

**Issue by bocharsky-bw** [whiteoctober/BreadcrumbsBundle#60]
There are a few PRs (https://github.com/whiteoctober/BreadcrumbsBundle/pull/30, https://github.com/whiteoctober/BreadcrumbsBundle/pull/31, https://github.com/whiteoctober/BreadcrumbsBundle/pull/32, https://github.com/whiteoctober/BreadcrumbsBundle/pull/33) from @THSeo for Oct 2013.

I think we have `itemClass` in order to config and use with Bootstrap3 as well, so I don't see a profit to merge this PRs. Could we close them at least?

P.S. @THSeo was active on GitHub more than a year ago.

**Comment by richsage** [comment]
Yep - done :-)
