### ISSUE TITLE
Possible to create dynamic namespace without exception

### ISSUE THREAD

**Issue by jced-artem** [whiteoctober/BreadcrumbsBundle#63]
Hello.
I had problem, when I created dynamic namespaces for differend user roles.
I would like propose to add this code in your repo:
into BreadcrumbsExtension class:

    public function getFunctions()
    {
        return array(
            new \Twig_SimpleFunction("wo_breadcrumbs", array($this, "getBreadcrumbs"), array("is_safe" => array("html"))),
            new \Twig_SimpleFunction("wo_render_breadcrumbs", array($this, "renderBreadcrumbs"), array("is_safe" => array("html"))),
            new \Twig_SimpleFunction("wo_breadcrumbs_exists", array($this, "hasBreadcrumbs"), array("is_safe" => array("html"))),
        );
    }

and method:

    public function hasBreadcrumbs($namespace = Breadcrumbs::DEFAULT_NAMESPACE)
    {
        return $this->breadcrumbs->hasNamespaceRegistered($namespace);
    }

and in Breadcrumbs model class:

    public function hasNamespaceRegistered($namespace = self::DEFAULT_NAMESPACE)
    {
        return isset($this->breadcrumbs[$namespace]);
    }

Thank you.

**Comment by bocharsky-bw** [comment]
Do you create dynamic namespaces in templates?

**Comment by jced-artem** [comment]
No, in controller, but I would like to check if namespace exists in template.

**Comment by bocharsky-bw** [comment]
To check is namespace breadcrumbs exists you could use `WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs::offsetExists()`, for example, in controller:

``` php
if ($this->get("white_october_breadcrumbs")->offsetExists(0, 'your_namespace')) {
    // do something
}
```

However it's a hack, so I opened PR https://github.com/whiteoctober/BreadcrumbsBundle/pull/64
