### ISSUE TITLE
Can we add a char limit to the configuration options?

### ISSUE THREAD

**Issue by rasanga** [whiteoctober/BreadcrumbsBundle#69]

**Comment by richsage** [comment]
Initially this feels like something you could easily do yourself by overriding the template.

But if it was included, it would also prompt other questions such as:

* Would you want truncation of each breadcrumb, or appending an ellipsis (...) if the crumb is too long?
* Would the limit apply to all crumbs, or eg everything apart from first and last

**Comment by rasanga** [comment]
Yes, I already done that by overriding the template. But it would be nice to have feature.

**Comment by richsage** [comment]
I think those other questions would need answering first. I'm not sure I'm keen on adding 3 new configuration options to cater for what is a quick template override currently. Could you outline your existing use case a bit further?

**Comment by richsage** [comment]
Closing due to non-activity.
