### ISSUE TITLE
Can we add diferent class to each item in the menu ?

### ISSUE THREAD

**Issue by lfaveur** [whiteoctober/BreadcrumbsBundle#73]
Hi good bundle but as you saw in the title i wanted add a class to each item in list, in order to do different action ... Because i want to add an auto completion on click on any item. My goal ... make dynamic breadcrumb, an user can modify it... I don't know if your bundle is the best solution ... is it ?

PS : Sorry for my bad english XD

**Comment by richsage** [comment]
You should be able to override the template - see the [overriding template](https://github.com/whiteoctober/BreadcrumbsBundle#overriding-the-template) section in the docs for details. Then you can add your own individual class as required.
