### ISSUE TITLE
Render Controller

### ISSUE THREAD

**Issue by bogdaniel** [whiteoctober/BreadcrumbsBundle#74]
Is it posible to call render controller on the action that holds the pagination and if yes then how because i'm getting this error: 

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "" as such route does not exist.") in @AppBundle\Survey\table_questions.html.twig at line 27.

**Comment by bocharsky-bw** [comment]
Hey @bogdaniel , looks like this issue doesn't relate to this bundle

**Comment by bogdaniel** [comment]
well on the line 27 i have 
{{ pagerfanta(pager, 'twitter_bootstrap3') }}
