### ISSUE TITLE
optional translation

### ISSUE THREAD

**Issue by wickedOne** [whiteoctober/BreadcrumbsBundle#76]
would it be of added value to make translations optional for a breadcrumb item?

```php
$breadcrumbs->addItem($user->getUsername(), '', [], false);
```
of course now the translator fails silently and simply outputs the input string, however, it does raise an additional ``translation.WARNING``

**Comment by loicdev** [comment]
+1

**Comment by loicdev** [comment]
I have found a temporary solution : Create your own template.
Copy the original one and remove :  
`| trans(b.translationParameters, translation_domain, locale)` 
at line 9.

In config.yml , you use the viewTemplate parameters and defined the path. ;)

**Comment by wickedOne** [comment]
thanks @loicdev for the suggestion!

i'm aware of your workaround but suggested this issue because i'd like to see this resolved out of the box rather than a override of the template

**Comment by loicdev** [comment]
Of course , it will be more cleaner ;)

**Comment by sampart** [comment]
If we had a lot of translation in the templates, turning them all into `if` blocks and only translating in certain circumstances would be a major change.  However, as @loicdev says, we only use the `trans` filter in one template, so this change would be okay.

Do feel free to make a PR for this and we'll review it.
