### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by tristanbes** [whiteoctober/BreadcrumbsBundle#83]
This bundle does not support Symfony4. Unless this bundle isn't maintained, which should be mentionned, Symfony4 should be added.

✌️

**Comment by sampart** [comment]
Hi @tristanbes, thanks for getting involved.  I've added a link to the (in-progress) PR that addresses this.

**Comment by mhujer** [comment]
@sampart this can be closed as the Symfony 4 support was merged in the linked PR.

**Comment by sampart** [comment]
Good spot.  Thanks, @mhujer.
