### ISSUE TITLE
Support PHP-PM by resetting state

### ISSUE THREAD

**Issue by Sander-Toonen** [whiteoctober/BreadcrumbsBundle#87]
When using this bundle with [php-pm](https://github.com/php-pm/php-pm) the breadcrumbs show alls paths that all previous users have visited. E.g:

> Home > Register > Home > Profile > Change Password > Home > Contact > Home > Contact, ... etc

This happens because `WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs` is a service that keeps state. Symfony 3.3 [added](https://github.com/symfony/symfony/pull/24155) a dependency injection tag that allows Symfony to call a `reset()`-method on the service after a request has been processed. This way, services can clean up any state so that a next request can be processed.

Symfony itself is already resetting certain services: https://github.com/symfony/symfony/issues/23984 

Since the Breadcrumbs class already has a `clear()` method that does exactly what is needed, adding the DI-tag should be all that is needed. I'll add a PR soon.

**Comment by isfett** [comment]
Would like to see this merged :)

**Comment by sampart** [comment]
Thanks all for your patience & contributions.  This is now in release https://github.com/whiteoctober/BreadcrumbsBundle/releases/tag/1.4.2.
