### ISSUE TITLE
Spaces between seperator and item

### ISSUE THREAD

**Issue by skbakker** [whiteoctober/BreadcrumbsBundle#89]
Hello,

I can't figure out how to add a space between the seperator and the items (left and right).

**Comment by sampart** [comment]
Could you add a note as to how you achieved this in the end?  That might help others who find this issue in future.  Thanks!

**Comment by skbakker** [comment]
With CSS.

I added padding to the seperator class on the span element.

`<span class="separator">/</span>`

CSS:

`.seperator {
padding: 0px 5px; 
}`

**Comment by sampart** [comment]
Thanks
